'use client';

import { useState, useEffect, useCallback, useMemo } from 'react';
import { createClient } from '@/utils/supabase/client';
import { DollarSign, TrendingUp, Package, Users, ArrowLeft, RefreshCw, Calendar, Euro } from 'lucide-react';
import Link from 'next/link';
import { useTranslation } from '@/lib/i18n/useTranslation';
import {
    LineChart,
    Line,
    AreaChart,
    Area,
    BarChart,
    Bar,
    XAxis,
    YAxis,
    CartesianGrid,
    Tooltip,
    Legend,
    ResponsiveContainer,
    ReferenceLine,
} from 'recharts';

type TimePeriod = 'all' | 'month' | 'year';

interface RevenueData {
    projects: any[];
    subscriptions: any[];
    allRevenues: any[];
    stats: {
        totalRevenue: number;
        totalProjects: number;
        totalSubscriptions: number;
        averageRevenue: number;
        currency: string;
    };
    groupedByDate: { date: string; revenue: number; count: number }[];
    groupedByUser: { userId: string; username: string; fullName: string; revenue: number; count: number }[];
    period: string;
}

export function RevenueAdminClient() {
    const { t, language } = useTranslation();
    const [timePeriod, setTimePeriod] = useState<TimePeriod>('all');
    const [data, setData] = useState<RevenueData | null>(null);
    const [loading, setLoading] = useState(true);
    const [refreshing, setRefreshing] = useState(false);
    const supabase = useMemo(() => createClient(), []);

    const loadData = useCallback(async (showRefreshing = false) => {
        try {
            if (showRefreshing) {
                setRefreshing(true);
            }
            const response = await fetch(`/api/admin/revenue?period=${timePeriod}`);
            
            if (!response.ok) {
                throw new Error('Erreur lors du chargement des revenus');
            }

            const revenueData = await response.json();
            setData(revenueData);
        } catch (error) {
            console.error('Error loading revenue:', error);
        } finally {
            setLoading(false);
            setRefreshing(false);
        }
    }, [timePeriod]);

    // Charger les données au montage
    useEffect(() => {
        loadData(true);
    }, [loadData]);

    // Rafraîchir automatiquement toutes les 60 secondes
    useEffect(() => {
        const interval = setInterval(() => {
            loadData();
        }, 60000); // 60 secondes

        return () => clearInterval(interval);
    }, [loadData]);

    const [chartType, setChartType] = useState<'area' | 'line' | 'bar'>('area');

    const periodLabels = {
        all: language === 'fr' ? 'Tout' : 'All',
        month: language === 'fr' ? '30 derniers jours' : 'Last 30 days',
        year: language === 'fr' ? '12 derniers mois' : 'Last 12 months',
    };

    // Fonction pour formater le montant
    const formatAmount = (amount: number, currency: string = 'USD') => {
        // Convertir de centimes en dollars
        const dollars = amount / 100;
        return new Intl.NumberFormat('en-US', {
            style: 'currency',
            currency: currency,
            minimumFractionDigits: 2,
            maximumFractionDigits: 2,
        }).format(dollars);
    };

    return (
        <div className="max-w-7xl mx-auto py-10 px-6 space-y-6">
            {/* Header */}
            <div>
                <Link
                    href="/admin"
                    className="inline-flex items-center gap-2 text-gray-600 hover:text-gray-900 mb-4 transition-colors"
                >
                    <ArrowLeft className="w-4 h-4" />
                    <span className="text-sm font-medium">
                        {language === 'fr' ? 'Retour au panneau admin' : 'Back to admin panel'}
                    </span>
                </Link>
                <div className="flex items-center justify-between">
                    <div>
                        <h1 className="text-3xl font-bold text-gray-900">
                            {language === 'fr' ? 'Revenus générés' : 'Generated Revenue'}
                        </h1>
                        <p className="text-gray-600 mt-2">
                            {language === 'fr' 
                                ? 'Suivi des revenus générés par les projets'
                                : 'Track revenue generated by projects'}
                        </p>
                    </div>
                    <button
                        onClick={() => loadData(true)}
                        disabled={refreshing}
                        className="inline-flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors disabled:opacity-50"
                    >
                        <RefreshCw className={`w-4 h-4 ${refreshing ? 'animate-spin' : ''}`} />
                        {language === 'fr' ? 'Actualiser' : 'Refresh'}
                    </button>
                </div>
            </div>

            {/* Filtres de période */}
            <div className="bg-white rounded-lg border border-gray-200 p-4">
                <div className="flex items-center gap-2 flex-wrap">
                    <Calendar className="w-5 h-5 text-gray-500" />
                    <span className="text-sm font-medium text-gray-700">
                        {language === 'fr' ? 'Période:' : 'Period:'}
                    </span>
                    {(['all', 'month', 'year'] as TimePeriod[]).map((period) => (
                        <button
                            key={period}
                            onClick={() => setTimePeriod(period)}
                            className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${
                                timePeriod === period
                                    ? 'bg-blue-600 text-white'
                                    : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                            }`}
                        >
                            {periodLabels[period]}
                        </button>
                    ))}
                </div>
            </div>

            {loading ? (
                <div className="text-center py-12">
                    <div className="inline-block animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
                    <p className="mt-4 text-gray-600">{language === 'fr' ? 'Chargement...' : 'Loading...'}</p>
                </div>
            ) : data ? (
                <>
                    {/* Statistiques principales */}
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
                        <StatCard
                            icon={<DollarSign className="w-6 h-6" />}
                            title={language === 'fr' ? 'Revenus totaux' : 'Total Revenue'}
                            value={formatAmount(data.stats.totalRevenue, data.stats.currency)}
                            color="green"
                        />
                        <StatCard
                            icon={<Package className="w-6 h-6" />}
                            title={language === 'fr' ? 'Projets payants' : 'Paid Projects'}
                            value={data.stats.totalProjects.toString()}
                            color="blue"
                        />
                        <StatCard
                            icon={<Users className="w-6 h-6" />}
                            title={language === 'fr' ? 'Abonnements actifs' : 'Active Subscriptions'}
                            value={(data.stats.totalSubscriptions || 0).toString()}
                            color="orange"
                        />
                        <StatCard
                            icon={<TrendingUp className="w-6 h-6" />}
                            title={language === 'fr' ? 'Revenu moyen' : 'Average Revenue'}
                            value={formatAmount(data.stats.averageRevenue, data.stats.currency)}
                            color="purple"
                        />
                    </div>

                    {/* Graphique des revenus par date */}
                    {data.groupedByDate.length > 0 && (
                        <div className="bg-white rounded-lg border border-gray-200 p-6 shadow-sm">
                            <div className="mb-6 flex items-center justify-between">
                                <div>
                                    <h2 className="text-xl font-semibold text-gray-900 mb-2">
                                        {language === 'fr' ? 'Évolution des revenus' : 'Revenue Evolution'}
                                    </h2>
                                    <p className="text-sm text-gray-500">
                                        {language === 'fr' 
                                            ? 'Visualisation de l\'évolution des revenus dans le temps'
                                            : 'Revenue trends over time visualization'}
                                    </p>
                                </div>
                                {/* Sélecteur de type de graphique */}
                                <div className="flex items-center gap-2 bg-gray-100 rounded-lg p-1">
                                    {(['area', 'line', 'bar'] as const).map((type) => (
                                        <button
                                            key={type}
                                            onClick={() => setChartType(type)}
                                            className={`px-3 py-1.5 text-sm font-medium rounded transition-colors ${
                                                chartType === type
                                                    ? 'bg-white text-gray-900 shadow-sm'
                                                    : 'text-gray-600 hover:text-gray-900'
                                            }`}
                                        >
                                            {type === 'area' 
                                                ? (language === 'fr' ? 'Aire' : 'Area')
                                                : type === 'line'
                                                ? (language === 'fr' ? 'Ligne' : 'Line')
                                                : (language === 'fr' ? 'Barres' : 'Bar')}
                                        </button>
                                    ))}
                                </div>
                            </div>
                            
                            {/* Graphique professionnel avec Recharts */}
                            <div className="w-full" style={{ height: '400px' }}>
                                <ResponsiveContainer width="100%" height="100%">
                                    {chartType === 'area' ? (
                                        <AreaChart
                                            data={data.groupedByDate}
                                            margin={{ top: 10, right: 30, left: 0, bottom: 60 }}
                                        >
                                            <defs>
                                                <linearGradient id="colorRevenue" x1="0" y1="0" x2="0" y2="1">
                                                    <stop offset="5%" stopColor="#10b981" stopOpacity={0.3}/>
                                                    <stop offset="95%" stopColor="#10b981" stopOpacity={0}/>
                                                </linearGradient>
                                            </defs>
                                            <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" opacity={0.5} />
                                            <XAxis 
                                                dataKey="date" 
                                                stroke="#6b7280"
                                                fontSize={12}
                                                tickLine={false}
                                                axisLine={false}
                                                angle={-45}
                                                textAnchor="end"
                                                height={80}
                                            />
                                            <YAxis 
                                                stroke="#6b7280"
                                                fontSize={12}
                                                tickLine={false}
                                                axisLine={false}
                                                tickFormatter={(value) => {
                                                    const dollars = value / 100;
                                                    if (dollars >= 1000) {
                                                        return `$${(dollars / 1000).toFixed(1)}k`;
                                                    }
                                                    return `$${dollars.toFixed(0)}`;
                                                }}
                                            />
                                            <Tooltip
                                                contentStyle={{
                                                    backgroundColor: '#fff',
                                                    border: '1px solid #e5e7eb',
                                                    borderRadius: '8px',
                                                    boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
                                                }}
                                                formatter={(value: any, name: string) => {
                                                    if (name === 'revenue') {
                                                        return [formatAmount(value, data.stats.currency), language === 'fr' ? 'Revenus' : 'Revenue'];
                                                    }
                                                    return [value, name];
                                                }}
                                                labelStyle={{ fontWeight: 600, color: '#111827' }}
                                            />
                                            <Area
                                                type="monotone"
                                                dataKey="revenue"
                                                stroke="#10b981"
                                                strokeWidth={3}
                                                fill="url(#colorRevenue)"
                                                name={language === 'fr' ? 'Revenus' : 'Revenue'}
                                                dot={{ fill: '#10b981', strokeWidth: 2, r: 4 }}
                                                activeDot={{ r: 6, stroke: '#10b981', strokeWidth: 2 }}
                                            />
                                            <ReferenceLine 
                                                y={data.stats.averageRevenue} 
                                                stroke="#8b5cf6" 
                                                strokeDasharray="5 5"
                                                label={{ 
                                                    value: language === 'fr' ? 'Moyenne' : 'Average', 
                                                    position: 'right',
                                                    fill: '#8b5cf6',
                                                    fontSize: 12,
                                                }}
                                            />
                                        </AreaChart>
                                    ) : chartType === 'line' ? (
                                        <LineChart
                                            data={data.groupedByDate}
                                            margin={{ top: 10, right: 30, left: 0, bottom: 60 }}
                                        >
                                            <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" opacity={0.5} />
                                            <XAxis 
                                                dataKey="date" 
                                                stroke="#6b7280"
                                                fontSize={12}
                                                tickLine={false}
                                                axisLine={false}
                                                angle={-45}
                                                textAnchor="end"
                                                height={80}
                                            />
                                            <YAxis 
                                                stroke="#6b7280"
                                                fontSize={12}
                                                tickLine={false}
                                                axisLine={false}
                                                tickFormatter={(value) => {
                                                    const dollars = value / 100;
                                                    if (dollars >= 1000) {
                                                        return `$${(dollars / 1000).toFixed(1)}k`;
                                                    }
                                                    return `$${dollars.toFixed(0)}`;
                                                }}
                                            />
                                            <Tooltip
                                                contentStyle={{
                                                    backgroundColor: '#fff',
                                                    border: '1px solid #e5e7eb',
                                                    borderRadius: '8px',
                                                    boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
                                                }}
                                                formatter={(value: any, name: string) => {
                                                    if (name === 'revenue') {
                                                        return [formatAmount(value, data.stats.currency), language === 'fr' ? 'Revenus' : 'Revenue'];
                                                    }
                                                    return [value, name];
                                                }}
                                                labelStyle={{ fontWeight: 600, color: '#111827' }}
                                            />
                                            <Line
                                                type="monotone"
                                                dataKey="revenue"
                                                stroke="#10b981"
                                                strokeWidth={3}
                                                dot={{ fill: '#10b981', strokeWidth: 2, r: 4 }}
                                                activeDot={{ r: 6, stroke: '#10b981', strokeWidth: 2 }}
                                                name={language === 'fr' ? 'Revenus' : 'Revenue'}
                                            />
                                            <ReferenceLine 
                                                y={data.stats.averageRevenue} 
                                                stroke="#8b5cf6" 
                                                strokeDasharray="5 5"
                                                label={{ 
                                                    value: language === 'fr' ? 'Moyenne' : 'Average', 
                                                    position: 'right',
                                                    fill: '#8b5cf6',
                                                    fontSize: 12,
                                                }}
                                            />
                                        </LineChart>
                                    ) : (
                                        <BarChart
                                            data={data.groupedByDate}
                                            margin={{ top: 10, right: 30, left: 0, bottom: 60 }}
                                        >
                                            <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" opacity={0.5} />
                                            <XAxis 
                                                dataKey="date" 
                                                stroke="#6b7280"
                                                fontSize={12}
                                                tickLine={false}
                                                axisLine={false}
                                                angle={-45}
                                                textAnchor="end"
                                                height={80}
                                            />
                                            <YAxis 
                                                stroke="#6b7280"
                                                fontSize={12}
                                                tickLine={false}
                                                axisLine={false}
                                                tickFormatter={(value) => {
                                                    const dollars = value / 100;
                                                    if (dollars >= 1000) {
                                                        return `$${(dollars / 1000).toFixed(1)}k`;
                                                    }
                                                    return `$${dollars.toFixed(0)}`;
                                                }}
                                            />
                                            <Tooltip
                                                contentStyle={{
                                                    backgroundColor: '#fff',
                                                    border: '1px solid #e5e7eb',
                                                    borderRadius: '8px',
                                                    boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
                                                }}
                                                formatter={(value: any, name: string) => {
                                                    if (name === 'revenue') {
                                                        return [formatAmount(value, data.stats.currency), language === 'fr' ? 'Revenus' : 'Revenue'];
                                                    }
                                                    return [value, name];
                                                }}
                                                labelStyle={{ fontWeight: 600, color: '#111827' }}
                                            />
                                            <Bar
                                                dataKey="revenue"
                                                fill="#10b981"
                                                radius={[8, 8, 0, 0]}
                                                name={language === 'fr' ? 'Revenus' : 'Revenue'}
                                            />
                                            <ReferenceLine 
                                                y={data.stats.averageRevenue} 
                                                stroke="#8b5cf6" 
                                                strokeDasharray="5 5"
                                                label={{ 
                                                    value: language === 'fr' ? 'Moyenne' : 'Average', 
                                                    position: 'right',
                                                    fill: '#8b5cf6',
                                                    fontSize: 12,
                                                }}
                                            />
                                        </BarChart>
                                    )}
                                </ResponsiveContainer>
                            </div>

                            {/* Statistiques supplémentaires sous le graphique */}
                            <div className="mt-6 pt-6 border-t border-gray-200 grid grid-cols-1 md:grid-cols-3 gap-4">
                                <div className="text-center">
                                    <p className="text-sm text-gray-500 mb-1">
                                        {language === 'fr' ? 'Période' : 'Period'}
                                    </p>
                                    <p className="text-lg font-semibold text-gray-900">
                                        {data.groupedByDate.length} {language === 'fr' ? 'points de données' : 'data points'}
                                    </p>
                                </div>
                                <div className="text-center">
                                    <p className="text-sm text-gray-500 mb-1">
                                        {language === 'fr' ? 'Revenu moyen' : 'Average Revenue'}
                                    </p>
                                    <p className="text-lg font-semibold text-gray-900">
                                        {formatAmount(data.stats.averageRevenue, data.stats.currency)}
                                    </p>
                                </div>
                                <div className="text-center">
                                    <p className="text-sm text-gray-500 mb-1">
                                        {language === 'fr' ? 'Revenu total' : 'Total Revenue'}
                                    </p>
                                    <p className="text-lg font-semibold text-green-600">
                                        {formatAmount(data.stats.totalRevenue, data.stats.currency)}
                                    </p>
                                </div>
                            </div>
                        </div>
                    )}

                    {/* Top développeurs par revenus */}
                    {data.groupedByUser.length > 0 && (
                        <div className="bg-white rounded-lg border border-gray-200">
                            <div className="p-4 border-b border-gray-200">
                                <h2 className="text-xl font-semibold text-gray-900">
                                    {language === 'fr' ? 'Top développeurs par revenus' : 'Top Developers by Revenue'}
                                </h2>
                            </div>
                            <div className="divide-y divide-gray-200">
                                {data.groupedByUser.slice(0, 10).map((user, index) => (
                                    <div key={user.userId} className="p-4 hover:bg-gray-50 transition-colors">
                                        <div className="flex items-center justify-between">
                                            <div className="flex items-center gap-4">
                                                <div className="w-10 h-10 rounded-full bg-blue-100 text-blue-600 flex items-center justify-center font-bold">
                                                    {index + 1}
                                                </div>
                                                <div>
                                                    <p className="font-medium text-gray-900">{user.fullName}</p>
                                                    <p className="text-sm text-gray-500">@{user.username}</p>
                                                </div>
                                            </div>
                                            <div className="text-right">
                                                <p className="font-semibold text-gray-900">
                                                    {formatAmount(user.revenue, data.stats.currency)}
                                                </p>
                                                <p className="text-sm text-gray-500">
                                                    {user.count} {language === 'fr' ? 'projets' : 'projects'}
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>
                    )}

                    {/* Liste des abonnements actifs */}
                    {data.subscriptions && data.subscriptions.length > 0 && (
                        <div className="bg-white rounded-lg border border-gray-200">
                            <div className="p-4 border-b border-gray-200">
                                <h2 className="text-xl font-semibold text-gray-900">
                                    {language === 'fr' ? 'Revenus des abonnements' : 'Subscription Revenue'}
                                </h2>
                            </div>
                            <div className="divide-y divide-gray-200 max-h-[400px] overflow-y-auto">
                                {data.subscriptions.slice(0, 50).map((revenue) => (
                                    <div key={revenue.id} className="p-4 hover:bg-gray-50 transition-colors">
                                        <div className="flex items-start justify-between">
                                            <div className="flex-1">
                                                <div className="flex items-center gap-2 mb-1">
                                                    <span className="text-sm font-medium text-gray-900">
                                                        {revenue.title}
                                                    </span>
                                                    <span className="px-2 py-0.5 bg-blue-100 text-blue-700 rounded text-xs">
                                                        {revenue.plan?.toUpperCase()}
                                                    </span>
                                                    {revenue.status && revenue.status !== 'active' && (
                                                        <span className="px-2 py-0.5 bg-gray-100 text-gray-600 rounded text-xs">
                                                            {revenue.status === 'canceled' 
                                                                ? (language === 'fr' ? 'Annulé' : 'Canceled')
                                                                : revenue.status === 'past_due'
                                                                ? (language === 'fr' ? 'En retard' : 'Past Due')
                                                                : revenue.status}
                                                        </span>
                                                    )}
                                                </div>
                                                <div className="flex items-center gap-4 text-xs text-gray-500 mt-1">
                                                    <span>
                                                        {revenue.fullName || revenue.username || 'N/A'}
                                                    </span>
                                                    {revenue.revenueDate && (
                                                        <span>
                                                            {new Date(revenue.revenueDate).toLocaleDateString(
                                                                language === 'fr' ? 'fr-FR' : 'en-US',
                                                                {
                                                                    day: '2-digit',
                                                                    month: 'short',
                                                                    year: 'numeric',
                                                                }
                                                            )}
                                                        </span>
                                                    )}
                                                    {revenue.months && (
                                                        <span>
                                                            {revenue.months} {language === 'fr' ? 'mois' : 'months'}
                                                        </span>
                                                    )}
                                                </div>
                                            </div>
                                            <div className="text-right">
                                                <p className="text-lg font-bold text-green-600">
                                                    {formatAmount(revenue.revenueAmount, revenue.revenueCurrency)}
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>
                    )}

                    {/* Liste des projets avec revenus */}
                    {data.projects && data.projects.length > 0 && (
                        <div className="bg-white rounded-lg border border-gray-200">
                            <div className="p-4 border-b border-gray-200">
                                <h2 className="text-xl font-semibold text-gray-900">
                                    {language === 'fr' ? 'Revenus des projets' : 'Project Revenue'}
                                </h2>
                            </div>
                            <div className="divide-y divide-gray-200 max-h-[400px] overflow-y-auto">
                                {data.projects.slice(0, 50).map((revenue) => (
                                    <div key={revenue.id} className="p-4 hover:bg-gray-50 transition-colors">
                                        <div className="flex items-start justify-between">
                                            <div className="flex-1">
                                                <div className="flex items-center gap-2 mb-1">
                                                    <span className="text-sm font-medium text-gray-900">
                                                        {revenue.title}
                                                    </span>
                                                    <span className="px-2 py-0.5 bg-green-100 text-green-700 rounded text-xs">
                                                        {language === 'fr' ? 'Projet' : 'Project'}
                                                    </span>
                                                </div>
                                                <div className="flex items-center gap-4 text-xs text-gray-500 mt-1">
                                                    <span>
                                                        {revenue.fullName || revenue.username || 'N/A'}
                                                    </span>
                                                    {revenue.revenueDate && (
                                                        <span>
                                                            {new Date(revenue.revenueDate).toLocaleDateString(
                                                                language === 'fr' ? 'fr-FR' : 'en-US',
                                                                {
                                                                    day: '2-digit',
                                                                    month: 'short',
                                                                    year: 'numeric',
                                                                }
                                                            )}
                                                        </span>
                                                    )}
                                                </div>
                                            </div>
                                            <div className="text-right">
                                                <p className="text-lg font-bold text-green-600">
                                                    {formatAmount(revenue.revenueAmount, revenue.revenueCurrency)}
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>
                    )}

                    {/* Message si aucun revenu */}
                    {(!data.projects || data.projects.length === 0) && (!data.subscriptions || data.subscriptions.length === 0) && (
                        <div className="bg-white rounded-lg border border-gray-200 p-8 text-center">
                            <p className="text-gray-500">
                                {language === 'fr' ? 'Aucun revenu disponible pour cette période' : 'No revenue available for this period'}
                            </p>
                        </div>
                    )}
                </>
            ) : (
                <div className="text-center py-12 text-gray-500">
                    {language === 'fr' ? 'Aucune donnée de revenus disponible' : 'No revenue data available'}
                </div>
            )}
        </div>
    );
}

function StatCard({
    icon,
    title,
    value,
    color,
}: {
    icon: React.ReactNode;
    title: string;
    value: string;
    color: 'green' | 'blue' | 'purple' | 'orange';
}) {
    const colorClasses = {
        green: 'bg-green-50 text-green-600',
        blue: 'bg-blue-50 text-blue-600',
        purple: 'bg-purple-50 text-purple-600',
        orange: 'bg-orange-50 text-orange-600',
    };

    return (
        <div className="bg-white rounded-lg border border-gray-200 p-6">
            <div className="flex items-center justify-between mb-4">
                <div className={`p-3 rounded-lg ${colorClasses[color]}`}>
                    {icon}
                </div>
            </div>
            <h3 className="text-sm font-medium text-gray-600 mb-1">{title}</h3>
            <p className="text-2xl font-bold text-gray-900">{value}</p>
        </div>
    );
}

